services:
  - type: web
    name: ibm-flask-dashboard
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k eventlet -w 1 unified_dashboard.app:app"
    plan: free
    branch: main
